version: '3'
services:
  shop:
    image: shabushabu/shop
    ports:
     - "8010:8010"
    links:
      - products
      - stock
  productcatalogue:
    image: shabushabu/products
    ports:
     - "8020:8020"
  stockmanager:
    image: shabushabu/stock
    ports:
     - "8030:8030"
