---
apiVersion: v1
kind: Service
metadata:
  name: products
  labels:
    app: products
spec:
  type: NodePort
  selector:
    app: products
  ports:
  - protocol: TCP
    port: 8020
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: products
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products
        image: shabushabu/javashop.products:1.0
        ports:
        - containerPort: 8020
        env:
          - name: SIGNALFX_AGENT_HOST
            valueFrom: 
              fieldRef:
                fieldPath: status.hostIP
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8025
          initialDelaySeconds: 30
          timeoutSeconds: 1
